jibo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    base_waist_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: base_waist_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    waist_body_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: waist_body_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    body_head_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: body_head_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
   
    